"""
Suggests where in a local codebase a system-impacting circular likely needs a code change.

This is the one piece of the project that's genuine RAG — everything else in the pipeline
is classification/extraction, not retrieval-augmented generation. See decisions.md (decision
11) for the full reasoning. Two things make this different from "embed the repo, do a
similarity search" the way most people would build it:

1. Embedding is hard-locked to a LOCAL Ollama model, in code, regardless of LLM_PROVIDER.
   A circular is a public regulatory document — fine to send to Claude. Proprietary code is
   not, even if the classification step happens to use a cloud provider. There is no
   settings.embedding_provider switch; only Ollama is wired here, on purpose.

2. Below-threshold results are reported as "no strong match — likely new functionality,"
   not force-ranked into a top-k list. A confidently wrong suggestion sends an engineer down
   a dead end, which is worse than no suggestion at all — same philosophy as the confidence-
   gated review queue elsewhere in this project.

Known real-world failure modes this tries to account for (and what it does NOT solve):
- Vocabulary drift between regulatory language ("UCC", "STP") and codebase naming
  (`client_id`, `SystematicTransferPlan`) — partially addressed via a small, extensible
  glossary (see BSE_TERM_GLOSSARY) that expands the query before embedding. This is a
  heuristic patch, not a solved problem — a real system would need this tuned per codebase.
- Granularity: whole-file embedding loses precision on large files; naive fixed-window
  chunking (no per-language AST parsing) loses some structure. A schema/constants file is
  biased toward via filename/path heuristics, not real static analysis.
- Repo drift: the index is a point-in-time snapshot. Re-run POST /repo-index/build after
  the codebase changes; there's no file-watcher or incremental re-index in this build.
"""
import hashlib
import json
import os
import time
from dataclasses import dataclass, asdict
from typing import Optional

import httpx

from app.config import settings


class RepoIndexError(Exception):
    """Raised for anything that prevents building or querying a repo index."""


# Directories that are pure noise for code-change retrieval — never worth indexing.
EXCLUDED_DIRS = {
    ".git", "node_modules", "venv", ".venv", "__pycache__", "dist", "build",
    "target", ".idea", ".vscode", ".pytest_cache", "vendor", "coverage",
    ".next", ".nuxt", "migrations",  # generated/autogenerated noise, not hand-authored logic
}

# Extensions worth embedding. Deliberately narrow — minified bundles, lockfiles, and
# binary assets would otherwise pollute the index with noise no engineer wants surfaced.
INCLUDED_EXTENSIONS = {
    ".py", ".rb", ".go", ".js", ".jsx", ".ts", ".tsx", ".java", ".rs",
    ".json", ".yml", ".yaml", ".sql", ".proto",
}

MAX_FILE_BYTES = 300 * 1024  # skip generated/vendored files masquerading as source
CHUNK_LINES = 120
CHUNK_OVERLAP_LINES = 20

# Cheap filename/path heuristics for biasing retrieval toward the kind of file a circular's
# language actually maps to. Not static analysis — a fast, transparent proxy for it.
FILE_TAG_HINTS = {
    "schema": ["schema", "serializer"],
    "constants": ["const", "enum", "config"],
    "validation": ["valid", "rule"],
    "model": ["model", "entity"],
    "api": ["controller", "handler", "route", "api", "endpoint"],
}

# A small, deliberately extensible bridge between BSE/regulatory language and common
# internal naming. This is a heuristic patch for vocabulary drift, not a general solution —
# real deployment would grow this per-codebase over time as retrieval misses get logged.
BSE_TERM_GLOSSARY = {
    "ucc": "unique client code client_id",
    "stp": "systematic transfer plan SystematicTransferPlan",
    "sip": "systematic investment plan SystematicInvestmentPlan",
    "swp": "systematic withdrawal plan SystematicWithdrawalPlan",
    "folio": "folio_number account",
    "nav": "net asset value nav_price",
    "amc": "asset management company fund_house",
    "rta": "registrar transfer agent registrar",
}


def _file_tag(path: str) -> str:
    lower = path.lower()
    for tag, hints in FILE_TAG_HINTS.items():
        if any(h in lower for h in hints):
            return tag
    return "general"


@dataclass
class Chunk:
    path: str
    start_line: int
    end_line: int
    text: str
    file_tag: str
    content_hash: str
    vector: Optional[list] = None


def _iter_source_files(root_path: str):
    # The index cache dir can legitimately live inside the repo being indexed (e.g.
    # REPO_INDEX_DIR=./repo_index pointed at this project's own root for local testing) —
    # without this, a rebuild would re-index its own previous output as "source," growing
    # unboundedly and reporting phantom changes every run.
    index_dir_abs = os.path.abspath(settings.repo_index_dir)

    for dirpath, dirnames, filenames in os.walk(root_path):
        if os.path.abspath(dirpath) == index_dir_abs:
            dirnames[:] = []
            continue
        dirnames[:] = [
            d for d in dirnames
            if d not in EXCLUDED_DIRS
            and not d.startswith(".")
            and os.path.abspath(os.path.join(dirpath, d)) != index_dir_abs
        ]
        for fname in filenames:
            ext = os.path.splitext(fname)[1]
            if ext not in INCLUDED_EXTENSIONS:
                continue
            full_path = os.path.join(dirpath, fname)
            try:
                if os.path.getsize(full_path) > MAX_FILE_BYTES:
                    continue
            except OSError:
                continue
            yield full_path


def _chunk_file(root_path: str, file_path: str) -> list[Chunk]:
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.read().splitlines()
    except OSError:
        return []

    if not lines:
        return []

    rel_path = os.path.relpath(file_path, root_path)
    tag = _file_tag(rel_path)
    chunks = []
    start = 0
    while start < len(lines):
        end = min(start + CHUNK_LINES, len(lines))
        text = "\n".join(lines[start:end])
        if text.strip():
            chunks.append(Chunk(
                path=rel_path,
                start_line=start + 1,
                end_line=end,
                text=text,
                file_tag=tag,
                content_hash=hashlib.sha256(text.encode("utf-8")).hexdigest(),
            ))
        if end == len(lines):
            break
        start = end - CHUNK_OVERLAP_LINES

    return chunks


_EMBED_BATCH_SIZE = 64  # cap per request - real batching via /api/embed's array input,
                         # not one HTTP round-trip per chunk


def _embed_texts(texts: list[str]) -> list[list[float]]:
    """
    Local-only embedding via Ollama. Deliberately does not accept a provider argument —
    see module docstring for why this is never routed through a cloud API.

    Uses /api/embed (current), not /api/embeddings (deprecated on current Ollama versions
    and returns a bare 404 there — confirmed directly against Ollama's own docs, not
    assumed). The two endpoints differ in more than the URL: /api/embed takes `input`
    (accepts a batch array) and returns `embeddings` (plural); the old one took a single
    `prompt` and returned `embedding` (singular). Real batching here also means indexing a
    repo is one request per _EMBED_BATCH_SIZE chunks, not one request per chunk.
    """
    if not texts:
        return []

    vectors: list[list[float]] = []
    for i in range(0, len(texts), _EMBED_BATCH_SIZE):
        batch = texts[i:i + _EMBED_BATCH_SIZE]
        try:
            resp = httpx.post(
                f"{settings.ollama_host.rstrip('/')}/api/embed",
                json={"model": settings.repo_embedding_model, "input": batch},
                timeout=120.0,
            )
            resp.raise_for_status()
        except httpx.ConnectError as e:
            raise RepoIndexError(
                f"Could not reach Ollama at {settings.ollama_host} for embeddings — is `ollama serve` running?"
            ) from e
        except httpx.HTTPError as e:
            raise RepoIndexError(f"Ollama embedding request failed: {e}") from e

        body = resp.json()
        batch_vectors = body.get("embeddings")
        if not batch_vectors or len(batch_vectors) != len(batch):
            raise RepoIndexError(
                f"Ollama returned {len(batch_vectors or [])} embedding(s) for {len(batch)} input(s) — "
                f"is '{settings.repo_embedding_model}' pulled? (ollama pull {settings.repo_embedding_model})"
            )
        vectors.extend(batch_vectors)

    return vectors


def _index_path(target: str) -> str:
    os.makedirs(settings.repo_index_dir, exist_ok=True)
    return os.path.join(settings.repo_index_dir, f"{target}.json")


def build_index(target: str, root_path: str) -> dict:
    """
    Builds (or incrementally refreshes) the local embedding index for a repo. Unchanged
    files are skipped via content hash, so re-running this after a small change doesn't
    re-embed the whole codebase.
    """
    if not root_path:
        raise RepoIndexError(f"No path configured for '{target}' repo.")
    if not os.path.isdir(root_path):
        raise RepoIndexError(f"'{root_path}' is not a local directory the app can read.")

    existing_by_hash: dict[str, Chunk] = {}
    index_file = _index_path(target)
    if os.path.exists(index_file):
        with open(index_file, "r") as f:
            prior = json.load(f)
        for c in prior.get("chunks", []):
            existing_by_hash[c["content_hash"]] = Chunk(**c)

    all_chunks: list[Chunk] = []
    files_seen = 0
    reused = 0
    newly_embedded = 0

    for file_path in _iter_source_files(root_path):
        files_seen += 1
        for chunk in _chunk_file(root_path, file_path):
            cached = existing_by_hash.get(chunk.content_hash)
            if cached is not None:
                all_chunks.append(cached)
                reused += 1
            else:
                all_chunks.append(chunk)
                newly_embedded += 1

    # Batch-embed only the chunks that don't already have a cached vector.
    to_embed = [c for c in all_chunks if c.vector is None]
    if to_embed:
        vectors = _embed_texts([c.text for c in to_embed])
        for c, v in zip(to_embed, vectors):
            c.vector = v

    with open(index_file, "w") as f:
        json.dump({
            "target": target,
            "root_path": root_path,
            "built_at": time.time(),
            "chunks": [asdict(c) for c in all_chunks],
        }, f)

    return {
        "target": target,
        "files_scanned": files_seen,
        "chunks_total": len(all_chunks),
        "chunks_reused": reused,
        "chunks_newly_embedded": newly_embedded,
    }


def index_status(target: str) -> Optional[dict]:
    index_file = _index_path(target)
    if not os.path.exists(index_file):
        return None
    with open(index_file, "r") as f:
        data = json.load(f)
    return {
        "target": target,
        "root_path": data.get("root_path"),
        "built_at": data.get("built_at"),
        "chunks_total": len(data.get("chunks", [])),
    }


def _cosine_sim(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(y * y for y in b) ** 0.5
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def _expand_query(text: str) -> str:
    """Appends glossary expansions for any BSE/regulatory terms found in the query, to
    narrow the vocabulary gap between circular language and codebase naming."""
    lower = text.lower()
    extras = [expansion for term, expansion in BSE_TERM_GLOSSARY.items() if term in lower]
    if not extras:
        return text
    return text + "\n\n" + " ".join(extras)


def search(target: str, query_text: str, top_k: int = 5, max_files: int = 3) -> dict:
    """
    Returns ranked candidate code locations for a query (a circular's key points/summary),
    or an explicit no-match result when nothing clears the similarity threshold — see module
    docstring for why that branch exists rather than always forcing a top-k list.
    """
    index_file = _index_path(target)
    if not os.path.exists(index_file):
        raise RepoIndexError(
            f"No index built for '{target}' yet. Run POST /repo-index/build first."
        )

    with open(index_file, "r") as f:
        data = json.load(f)
    chunks = data.get("chunks", [])
    if not chunks:
        return {"matched": False, "reason": "Index is empty (no indexable source files found).", "candidates": []}

    expanded_query = _expand_query(query_text)
    query_vector = _embed_texts([expanded_query])[0]

    scored = []
    for c in chunks:
        score = _cosine_sim(query_vector, c["vector"])
        scored.append((score, c))
    scored.sort(key=lambda x: x[0], reverse=True)

    top_score = scored[0][0] if scored else 0.0
    if top_score < settings.repo_similarity_threshold:
        return {
            "matched": False,
            "reason": (
                f"Nothing in the '{target}' codebase scored above the similarity threshold "
                f"({top_score:.2f} < {settings.repo_similarity_threshold}). This likely "
                "describes new functionality rather than a change to existing code."
            ),
            "candidates": [],
        }

    candidates = []
    seen_files = set()
    for score, c in scored:
        if len(seen_files) >= max_files and c["path"] not in seen_files:
            continue
        if len(candidates) >= top_k:
            break
        seen_files.add(c["path"])
        candidates.append({
            "path": c["path"],
            "start_line": c["start_line"],
            "end_line": c["end_line"],
            "file_tag": c["file_tag"],
            "score": round(score, 4),
            "snippet": c["text"][:400],
        })

    return {"matched": True, "reason": None, "candidates": candidates}
